# Generated by Django 5.2 on 2025-04-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
